### ISSUE TITLE
Invalid data found when processing input: clip-list.txt

### ISSUE THREAD

**Issue by gardner** [data-doge/mementoize#1]
Looks like it's failing to write the clip-list.txt. The file exists but is empty.

```
gardner@sneaker:~$ mementoize "https://www.youtube.com/watch?v=D6pN6x6pGwA"
/Users/gardner/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/index.js:88
      if (err) throw err;
               ^

Error: Command failed: ffmpeg -f concat -i /Users/gardner/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/tmp/clip-list.txt -vcodec copy -acodec copy -y /Users/gardner/output.mp4
ffmpeg version 3.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.3.0 (clang-703.0.31)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --disable-lzma --enable-vda
  libavutil      55. 27.100 / 55. 27.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 40.101 / 57. 40.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.102 /  6. 46.102
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
/Users/gardner/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/tmp/clip-list.txt: Invalid data found when processing input

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

gardner@sneaker:~$ cat /Users/gardner/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/tmp/clip-list.txt
gardner@sneaker:~$ ls -la /Users/gardner/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/tmp/clip-list.txt
-rw-r--r--  1 gardner  staff  0 Aug 21 12:03 /Users/gardner/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/tmp/clip-list.txt
gardner@sneaker:~$ which ffmpeg
/usr/local/bin/ffmpeg
gardner@sneaker:~$ 
```

**Comment by gardner** [comment]
The tmp dir doesn't have the clips in it:

```
gardner@sneaker:~/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/tmp ((v0.30.2))$ ls -lah
total 53784
drwxr-xr-x  4 gardner  staff   136B Aug 21 12:11 .
drwxr-xr-x  4 gardner  staff   136B Aug 21 12:11 ..
-rw-r--r--  1 gardner  staff     0B Aug 21 12:11 clip-list.txt
-rw-r--r--  1 gardner  staff    26M Aug 21 12:11 original.mp4
gardner@sneaker:~/.nvm/versions/node/v5.9.0/lib/node_modules/mementoize/lib/bin/tmp ((v0.30.2))$ 
```

**Comment by data-doge** [comment]
fuuuuuuuc

**Comment by gardner** [comment]
i'm digging into it right now. after setting up an environment with `npm link` everything seems to be working. now i am getting a different error from ffmpeg about `Unsafe filename`. i'll report back when I find more.

**Comment by data-doge** [comment]
ahhhh i think i know whats wrong

on line 34:

``` js
video.on('info', (info) => {
  duration = info.duration
})
```

if a video is shorter than a minute (like the doc chicken one in the readme), then `info.duration` spits out a number (in seconds) -- but if its longer than a minute, than it spits out `10:59` or some shit. and then things break

**Comment by data-doge** [comment]
fixed in https://github.com/data-doge/mementoize/commit/3c3e409d4f77cb8d1f11fa48cdc67a672098b0c1
