### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by gardner** [data-doge/mementoize#2]
looks like a path issue 

```
gardner@sneaker:~/src/mementoize (master)$ npm i

> fsevents@1.0.14 install /Users/gardner/src/mementoize/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/gardner/src/mementoize/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> youtube-dl@1.11.1 postinstall /Users/gardner/src/mementoize/node_modules/youtube-dl
> node ./scripts/download.js

Downloaded youtube-dl 2016.08.19

> mementoize@1.1.0 prepublish /Users/gardner/src/mementoize
> babel src/bin/index.js --out-file lib/bin/index.js

Error: ENOENT: no such file or directory, open 'lib/bin/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at output (/Users/gardner/src/mementoize/node_modules/babel-cli/lib/babel/file.js:89:10)
    at walk (/Users/gardner/src/mementoize/node_modules/babel-cli/lib/babel/file.js:140:5)
    at files (/Users/gardner/src/mementoize/node_modules/babel-cli/lib/babel/file.js:146:7)
    at module.exports (/Users/gardner/src/mementoize/node_modules/babel-cli/lib/babel/file.js:170:5)
    at Object.<anonymous> (/Users/gardner/src/mementoize/node_modules/babel-cli/lib/babel/index.js:131:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/gardner/.nvm/versions/node/v5.9.0/bin/node" "/Users/gardner/.nvm/versions/node/v5.9.0/bin/npm" "i"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! mementoize@1.1.0 prepublish: `babel src/bin/index.js --out-file lib/bin/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mementoize@1.1.0 prepublish script 'babel src/bin/index.js --out-file lib/bin/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mementoize package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src/bin/index.js --out-file lib/bin/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mementoize
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mementoize
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gardner/src/mementoize/npm-debug.log
```

**Comment by gardner** [comment]
This is worked around with:
mkdir -p lib/bin
touch lib/bin/index.js
npm i
